@startwbs
title Data.gov.be PBS

* New Data.gov.be portal
** Back-end
*** Harvesters / portal scrapers
****[#LightBlue] Scraper tools
****[#LightBlue] SKOS mappings
****[#LightBlue] SPARQL scripts
****[#LightBlue] Documentation
*** SHACL validator
****[#LightBlue] SHACL validation ruleset
****[#LightBlue] Report publicatin tool
*** DCAT-AP exporter (to EDP)
****[#LightBlue] Export tool
****[#LightBlue] Documentation
*** REST uploader (to data.gov.be)
****[#LightBlue] Upload tool
****[#LightBlue] Documentation
** Portal frond-end
*** Analysis
****[#LightBlue] Analysis document
*** Look'n'feel
****[#LightYellow] Wireframes
****[#LightYellow] CSS / layout
****[#LightYellow] Accessibility statement
*** Website configuration
****[#LightYellow] Module configuration
****[#LightYellow] Menu configuration
****[#LightYellow] Views / lists configuration
****[#LightYellow] Faceted search configuration
****[#LightYellow] Content typee configuration
****[#LightYellow] Statistics configuration
*** Content
****[#LightBlue] News items
****[#LightBlue] User stories
****[#LightBlue] Additional info and FAQ
****[#LightBlue] Translations
*** REST upload service
****[#LightYellow] Service configuration
****[#LightBlue] Documentation
** Communication
***[#LightBlue] Press release

legend top right
Product of:
<back:LightBlue>   FPS BOSA   </back>

<back:LightYellow>   Supplier  </back>
end legend

@endwbs
