@startuml
title "Work Breakdown Structure"

@startwbs
* New Data.gov.be portal
** Back-end
*** Harvesters / portal scrapers
****[#LightBlue] Write scraping tools
****[#LightBlue] Define additonal SKOS mappings
****[#LightBlue] Write addional SPARQL scripts
****[#LightBlue] Write and perform tests
****[#LightBlue] Write documentation
****[#LightBlue] Automate the process
*** SHACL validator
****[#LightBlue] Define validation ruleset
****[#LightBlue] Write and perform tests
****[#LightBlue] Automate publishing of reports
*** DCAT-AP export (to EDP)
****[#LightBlue] Automate publishing of export
****[#LightBlue] Write documentation
*** REST uploader (to data.gov.be)
****[#LightBlue] Automate uploading of datasets
****[#LightBlue] Write documentation
** Portal frond-end
*** Analysis
****[#LightBlue] Perform initial analysis
*** Look'n'feel
****[#LightYellow] Create wireframes
****[#LightYellow] Create CSS / layout
****[#LightYellow] Test accessibility
*** Website configuration
****[#LightYellow] Configure modules
****[#LightYellow] Configure menus
****[#LightYellow] Configure views / lists
****[#LightYellow] Configure faceted search
****[#LightYellow] Configure content types
****[#LightYellow] Configure statistics
*** Content
****[#LightBlue] Add news items
****[#LightBlue] Add user stories
****[#LightBlue] Add additional info and FAQ
****[#LightBlue] Check translations
*** REST upload service
****[#LightYellow] Configure services
****[#LightBlue] Test automation of uploading
****[#LightBlue] Write documentation
@endwbs
@enduml
